### ISSUE TITLE
This seems to fail could you make an example for where it works?

### ISSUE THREAD

**Issue by killerfrienddk** [joaoantoniomartinsfilho/quartz-redis-store#1]
["quartz.jobStore.type"] = $"{nameof(RedisJobStore)}, {nameof(JobStore)}",

**Comment by jmartins-sh** [comment]
Hey @killerfrienddk, sorry the delay, I just pushed a new package's version in nuget, could you please update your version?

About the JobStore Type, It was wrong, thanks! You can use the following: 

`["quartz.jobStore.type"] = "QuartzRedis.Store.RedisJobStore, QuartzRedis.Store"`

Let me know if you need any help!

**Comment by jmartins-sh** [comment]
hey @killerfrienddk, I am closing the issue, but if something went wrong just re-open it
